### ISSUE TITLE
Exception in thread Thread-95:

### ISSUE THREAD

**Issue by Luwenjian888** [wavefrontshaping/slmPy#3]
Sorry for  presenting my problem incorrectly. And I complete my problem here.
I got an Exception when I used the example code given by you to control my spatial light modulator. Actually this code still work although it gives this Exception. I don't know if it is normal so I submit this issues.

**Example code:**

import slmpy
import time
import numpy as np
slm = slmpy.SLMdisplay(isImageLock = True)
resX, resY = slm.getSize()
ImgResX = resX//2
ImgResY = resY//2
X,Y = np.meshgrid(np.linspace(0,ImgResX,ImgResX),np.linspace(0,ImgResY,ImgResY))
for i in range(100):
  testIMG = np.round((2**8-1)*(0.5+0.5*np.sin(2*np.pi*X/50+1.0*i/10*np.pi))).astype('uint8')
  slm.updateArray(testIMG)
  time.sleep(0.05)
slm.close()

**Exception:**
Exception in thread Thread-95:
Traceback (most recent call last):
  File "C:\Users\OPTLAB\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\lwj\SLM\slmpy.py", line 145, in run
    app.MainLoop()
  File "C:\Users\OPTLAB\anaconda3\lib\site-packages\wx\core.py", line 2237, in MainLoop
    rv = wx.PyApp.MainLoop(self)
wx._core.wxAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\msw\thread.cpp(1333) in wxMutexGuiLeaveOrEnter(): only main thread may call wxMutexGuiLeaveOrEnter()!

**Comment by fschiffers** [comment]
Hello Sebastian,

thank you writing this great tool. Really easy to use !

I've encountered the same problem when using your command slm.close() as follows:
`    rv = wx.PyApp.MainLoop(self)
wx._core.wxAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\msw\thread.cpp(1333) in wxMutexGuiLeaveOrEnter(): only main thread may call wxMutexGuiLeaveOrEnter()!`

I assume that this is not really much of a problem (as you've described above) since this only happens when closing the SLM and restarting the SLM with the SLMDisplay ( e.g. via slmpy.SLMdisplay(monitor = 1, isImageLock = True) ) works flawlessly.

I will look into a way how to catch this exception and prevent it from printing into the command line since I imagine it also confused other people. I will update you here if I find a solution.
